services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "5001:5000"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - auth_service

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
    volumes:
      - "./auth_service:/app"
    environment:
      - DEBUG=True
  
  post-service:
    build: 
      context: ./post-service
    volumes:
      - post_app_data:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=post-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=post_db
      - DB_PORT=5432
    depends_on:
      - post-db

  post-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  post_app_data: