services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - auth_service

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
    volumes:
      - "./auth_service:/app"
    environment:
      - DEBUG=True

  post-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: